### PR TITLE
Add Iterable subtype bound to FromInput

### PR DESCRIPTION
**Pull request by ubaldop**
As a precondition for the enhancement suggested [here](https://github.com/sangria-graphql/sangria/issues/979), this adds slight improvements to the `FromInput` trait, namely:

- introduction of an `Iterable` subtype bound
- introduction of a new implicit, i.e.: `iterableInput`
- loosen type in `mapAndMarshal` signature

### CODE REVIEW

**Comment by yanns** [comment]
I kind of missed that PR. I guess it's still actual?

**Comment by ubaldop** [comment]
if https://github.com/sangria-graphql/sangria/issues/979 is still needed, yes :)

**Review by yanns — APPROVED** [review]
Let's try out then!

**Comment by yanns** [comment]
could you rebase it on the new `main`?

**Comment by ubaldop** [comment]
> could you rebase it on the new `main`?

done

**Comment by yanns** [comment]
You need to add some exceptions in the mina binary checks:
https://github.com/sangria-graphql/sangria-marshalling-api/actions/runs/10774639006/job/29877690179?pr=160

Ex how to do it: https://github.com/sangria-graphql/sangria/blob/2f5aa8b457dd522530ab45689e1a83fdf176a152/build.sbt#L96

**Pull request merged**
